; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_untitled=music_data_untitled
.endif

music_data_untitled:
	.byte 1
	.word @instruments
	.word @instruments_exp
	.word @samples-104
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch8,@song0ch9,@song0ch10 ; 00 : Song 1
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_untitled
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env7,@env11,@env14,@env0 ; 00 : Blank
	.word @env13,@env11,@env16,@env0 ; 01 : Crazy Arps
	.word @env2,@env8,@env20,@env0 ; 02 : Crazy Arps 1
	.word @env18,@env21,@env9,@env0 ; 03 : V Dah
	.word @env1,@env15,@env14,@env0 ; 04 : V Dah 1

@instruments_exp:
	.word @env4, @env5, @env10 ; 00 : d-drum
	.word @instrument_epsm_extra_patch5
	.byte $3c,$c0,$00,$00,$1f,$00,$00,$07
	.word @env3, @env11, @env0 ; 01 : d-Hi-Hat
	.word @instrument_epsm_extra_patch6
	.byte $38,$c0,$00,$00,$1f,$00,$00,$07
	.word @env3, @env11, @env0 ; 02 : d-Hi-Hat 1
	.word @instrument_epsm_extra_patch7
	.byte $38,$c0,$00,$00,$1f,$00,$00,$07
	.word @env19, @env12, @env6 ; 03 : d-Kick
	.word @instrument_epsm_extra_patch8
	.byte $20,$c0,$00,$00,$1f,$00,$00,$07
	.word @env17, @env21, @env0 ; 04 : Saw 2 - LR 2
	.word @instrument_epsm_extra_patch9
	.byte $3c,$c0,$00,$15,$1f,$00,$00,$0f
	.word @env7, @env11, @env0 ; 05 : Sub-Bass
	.word @instrument_epsm_extra_patch10
	.byte $07,$c0,$00,$04,$1f,$00,$00,$0f

@instrument_epsm_extra_patch5:
	.byte $00,$00,$00,$1f,$11,$11,$27,$00,$00,$7f,$1f,$0a,$00,$ff,$00,$01,$00,$1f,$1f,$10,$0f,$00,$00
@instrument_epsm_extra_patch6:
	.byte $00,$00,$00,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$0f,$08,$1f,$13,$1a,$cf,$00,$00
@instrument_epsm_extra_patch7:
	.byte $00,$00,$00,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$0f,$05,$1f,$13,$0c,$9f,$00,$00
@instrument_epsm_extra_patch8:
	.byte $00,$00,$00,$1f,$00,$00,$07,$00,$00,$35,$1f,$16,$14,$0f,$00,$00,$00,$1f,$1f,$10,$0f,$00,$00
@instrument_epsm_extra_patch9:
	.byte $00,$00,$00,$1f,$00,$00,$0f,$00,$70,$7f,$1f,$1c,$00,$0c,$04,$70,$7f,$1f,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch10:
	.byte $00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$0f,$00,$00,$7f,$1f,$00,$00,$06,$00,$00

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$06,$0d,$00	;26 (bde)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$06,$0f,$00	;27 (bde)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;28 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;29 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;30 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;31 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;32 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;33 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;34 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;35 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;36 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;37 
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;38 
	.byte $02+.lobyte(FAMISTUDIO_DPCM_PTR),$1c,$0f,$00	;39 (snare15.dmc)

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$c7,$c5,$c0,$02,$cf,$c5,$c1,$c0,$02,$cf,$ce,$cd,$c6,$c5,$c4,$cf,$c5,$c1,$c0,$c0,$c0,$00,$01
@env2:
	.byte $00,$cf,$02,$c3,$02,$cb,$02,$c3,$c3,$c3,$00,$01
@env3:
	.byte $00,$cc,$7f,$00,$02
@env4:
	.byte $00,$cc,$08,$c0,$00,$03
@env5:
	.byte $c0,$b9,$b6,$b4,$b1,$af,$ac,$00,$06
@env6:
	.byte $80,$80,$90,$af,$c0,$00,$04
@env7:
	.byte $00,$cf,$7f,$00,$02
@env8:
	.byte $cc,$c0,$c0,$cc,$c0,$c0,$00,$00
@env9:
	.byte $c2,$05,$c0,$05,$c1,$04,$c1,$00,$00
@env10:
	.byte $80,$80,$90,$b6,$c0,$00,$04
@env11:
	.byte $c0,$7f,$00,$01
@env12:
	.byte $c0,$b9,$b6,$b2,$ae,$00,$04
@env13:
	.byte $00,$cf,$cf,$ce,$cd,$cc,$cb,$00,$01
@env14:
	.byte $7f,$00,$00
@env15:
	.byte $c2,$02,$c0,$13,$c0,$00,$00
@env16:
	.byte $c2,$02,$c1,$02,$c0,$02,$c0,$00,$00
@env17:
	.byte $00,$cb,$7f,$00,$02
@env18:
	.byte $00,$cf,$ce,$cb,$c0,$c0,$c0,$00,$01
@env19:
	.byte $00,$cf,$05,$c0,$00,$03
@env20:
	.byte $c2,$05,$c0,$05,$c1,$05,$c2,$05,$c0,$05,$c1,$04,$c1,$00,$00
@env21:
	.byte $cc,$c0,$00,$01

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $73, $4d, $01, $ff, $99, $82, $19, $83, $43, $1d, $83, $43
	.byte $22, $83, $43, $25, $83, $43, $29, $83, $43, $2e, $83, $43, $31, $47, $83, $43, $35, $83, $50, $02, $70
@song0ref46:
	.byte $34, $83, $43, $2e, $83, $43, $2a, $83, $43, $2e, $83, $43, $34, $83, $43, $2e, $83, $43, $2a, $83, $43, $2e, $83, $43
	.byte $34, $83, $43, $2e, $83, $43, $2a, $83, $43, $2e, $83, $43, $34, $83, $43, $2e, $83, $43, $2a, $83, $43, $2e, $81, $81
	.byte $43, $33, $83, $43, $2e, $83, $43, $2a, $83, $43, $2e, $83, $43, $33, $83, $43, $2e, $83, $00, $7f, $4d, $00, $80, $09
	.byte $95, $4f, $7f, $21, $0a, $95, $47, $86
@song0ref126:
	.byte $40, $0a, $a1, $0a, $a1, $40, $0a, $a1, $0a, $b9, $40, $0a, $95, $47, $40, $0a, $a1, $0a, $a1, $40, $0a, $a1, $0a, $b9
	.byte $40, $0a, $95, $47, $40, $0a, $a1, $0a, $a1, $40, $0a, $a1, $0a, $b9, $40, $0a, $95, $47, $06, $dd, $0c, $ad, $05, $ad
	.byte $47
	.byte $41, $24
	.word @song0ref126
	.byte $47
	.byte $41, $24
	.word @song0ref126
	.byte $47
	.byte $41, $1e
	.word @song0ref126
	.byte $47, $40, $0a, $a1, $00, $ff, $99
@song0ch0loop:
	.byte $00, $42
	.word @song0ch0loop
@song0ch1:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $79, $ff, $8f, $82, $19, $83, $43, $1d, $83, $43, $22, $83, $43, $25, $83, $43
	.byte $29, $83, $43, $2e, $83, $43, $31, $83, $43, $35, $83, $50, $02, $d0
	.byte $41, $2d
	.word @song0ref46
	.byte $43, $2a, $83, $43, $2e, $83, $43, $2d, $83, $43, $29, $83, $43, $24, $83, $43, $29, $83, $43, $2d, $83, $43, $29, $83
	.byte $43, $24, $83, $43, $29, $83, $84
@song0ref270:
	.byte $2e, $89, $43, $29, $89, $43, $25, $89, $43, $22, $89, $43, $2e, $89, $43, $29, $89, $43, $25, $89, $43, $22, $89, $43
	.byte $2e, $89, $43, $29, $89, $43, $25, $89, $43, $22, $89, $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
@song0ref317:
	.byte $34, $89, $43, $2e, $89, $43, $2a, $89, $43, $28, $89, $43, $34, $89, $43, $2e, $89, $43, $2a, $89, $43, $28, $89, $43
	.byte $24, $89, $43, $2a, $89, $43, $2e, $89, $43, $33, $89, $43, $1d, $89, $43, $24, $89, $43, $29, $89, $43, $2d, $89, $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $41, $20
	.word @song0ref317
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $43
	.byte $41, $18
	.word @song0ref270
	.byte $41, $20
	.word @song0ref317
	.byte $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch1loop:
	.byte $00, $42
	.word @song0ch1loop
@song0ch2:
	.byte $ff, $bf, $ff, $bf, $80
@song0ref421:
	.byte $0a, $89
@song0ref423:
	.byte $16, $83, $00, $83, $16, $83, $00, $83, $16, $83, $00, $83, $22, $83, $00, $83, $22, $83, $00, $83, $16, $83, $00, $83
	.byte $16, $83, $00, $83, $0a, $83, $00, $83, $16, $83, $00, $83
	.byte $41, $18
	.word @song0ref423
	.byte $41, $26
	.word @song0ref421
	.byte $41, $18
	.word @song0ref423
	.byte $41, $26
	.word @song0ref421
	.byte $41, $18
	.word @song0ref423
@song0ref474:
	.byte $06, $89, $12, $83, $00, $83, $12, $83, $00, $83, $06, $89, $12, $83, $00, $83, $12, $83, $00, $83, $06, $89, $12, $83
	.byte $00, $83, $0c, $83, $00, $83, $18, $83, $00, $83, $18, $83, $00, $83, $18, $89, $4f, $7f, $2f, $18, $83, $00, $83, $09
	.byte $89, $4f, $7f, $2f, $18, $83, $00, $83, $4f, $7f, $2f, $18
@song0ref534:
	.byte $83, $00, $83
@song0ref537:
	.byte $0a, $89, $00, $95, $0a, $89, $00, $95, $0a, $89, $00, $95, $16, $89, $00, $95, $16, $83, $00, $83, $16, $83, $00, $83
	.byte $0a, $89, $00, $89, $0a, $89, $16, $83, $00, $8f, $0a, $89, $00, $95, $0a, $89, $00, $95, $16, $83, $00, $83, $16, $83
	.byte $00, $83, $0a, $83, $00, $83, $0a, $89, $00, $89, $0a, $83, $00, $83, $0a
	.byte $41, $1f
	.word @song0ref534
	.byte $41, $1e
	.word @song0ref474
@song0ref606:
	.byte $24, $83, $00, $83, $24, $83, $00, $83, $24, $89, $05, $83, $00, $83, $1d, $83, $00, $83, $1d, $83, $00, $83, $1d, $89
	.byte $41, $3f
	.word @song0ref537
	.byte $41, $1f
	.word @song0ref534
	.byte $41, $1e
	.word @song0ref474
	.byte $41, $18
	.word @song0ref606
	.byte $41, $3f
	.word @song0ref537
	.byte $41, $1f
	.word @song0ref534
	.byte $41, $1e
	.word @song0ref474
	.byte $41, $18
	.word @song0ref606
	.byte $41, $3f
	.word @song0ref537
	.byte $41, $1f
	.word @song0ref534
	.byte $41, $1a
	.word @song0ref474
	.byte $11, $ad, $43, $4f, $7f, $1d, $0a, $95, $00, $95
@song0ch2loop:
	.byte $00, $42
	.word @song0ch2loop
@song0ch3:
	.byte $ff, $bf, $ff, $bf, $7a, $88, $32, $ff, $bd, $32, $ff, $bd, $32, $ff, $bd, $32, $dd, $77, $80, $4f, $0a, $30, $3f, $ad
	.byte $50, $05, $e0, $4f, $f6, $3f, $30, $ad, $7a, $84
@song0ref712:
	.byte $33, $ff, $bd, $33, $ff, $bd, $33, $ff, $bd, $33, $dd, $7d, $4f, $f5, $3f, $20, $dd, $7a, $33, $ff, $bd, $33, $ff, $bd
	.byte $33, $ff, $bd, $33, $dd, $7d, $4f, $f5, $3f, $20, $dd, $7a
	.byte $41, $18
	.word @song0ref712
	.byte $7d, $80, $4f, $0a, $30, $3f, $ad, $84, $4f, $f6, $3f, $38, $95, $43, $4f, $f5, $38, $30, $95
@song0ch3loop:
	.byte $00, $42
	.word @song0ch3loop
@song0ch4:
@song0ref775:
	.byte $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1
	.byte $41, $18
	.word @song0ref775
	.byte $41, $18
	.word @song0ref775
	.byte $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $a1, $1a, $89, $00, $d1
@song0ref825:
	.byte $00, $ad, $27, $89, $00, $d1, $27, $89, $00, $a1, $00, $ad, $27, $89, $00, $d1, $27, $89, $00, $a1, $00, $ad, $27, $89
	.byte $00, $d1, $27, $89, $00, $a1, $af, $27, $89, $00, $d1, $27, $89, $00, $89, $27, $89, $27, $89
	.byte $41, $2b
	.word @song0ref825
	.byte $41, $2b
	.word @song0ref825
	.byte $41, $1e
	.word @song0ref825
	.byte $27, $89, $00, $95, $27, $89, $00, $95, $27, $89, $27, $89, $27, $89, $00, $d1
@song0ch4loop:
	.byte $00, $42
	.word @song0ch4loop
@song0ch5:
@song0ref898:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ch5loop:
	.byte $00, $42
	.word @song0ch5loop
@song0ch6:
	.byte $41, $2c
	.word @song0ref898
@song0ch6loop:
	.byte $00, $42
	.word @song0ch6loop
@song0ch7:
	.byte $41, $2c
	.word @song0ref898
@song0ch7loop:
	.byte $00, $42
	.word @song0ch7loop
@song0ch8:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $88
@song0ref976:
	.byte $16, $89, $00, $95, $16, $89, $00, $95, $16, $89, $00, $95, $22, $89, $00, $95, $22, $83, $00, $83, $22, $83, $00, $83
	.byte $16, $89, $00, $89, $16, $89, $22, $83, $00, $8f, $16, $89, $00, $95, $16, $89, $00, $95, $22, $83, $00, $83, $22, $83
	.byte $00, $83, $16, $83, $00, $83, $16, $89, $00, $89, $16, $83, $00, $83, $16, $83, $00, $83
	.byte $41, $1c
	.word @song0ref976
@song0ref1045:
	.byte $12, $89, $1e, $83, $00, $83, $1e, $83, $00, $83, $12, $89, $1e, $83, $00, $83, $1e, $83, $00, $83, $12, $89, $1e, $83
	.byte $00, $83, $18, $83, $00, $83, $30, $83, $00, $83, $30, $83, $00, $83, $30, $89, $11, $83, $00, $83, $29, $83, $00, $83
	.byte $29, $83, $00, $83, $29, $89
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $36
	.word @song0ref1045
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $36
	.word @song0ref1045
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $1a
	.word @song0ref1045
	.byte $1d, $ad, $11, $ad
@song0ch8loop:
	.byte $00, $42
	.word @song0ch8loop
@song0ch9:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $8a
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $36
	.word @song0ref1045
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $36
	.word @song0ref1045
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $41, $36
	.word @song0ref1045
	.byte $41, $42
	.word @song0ref976
	.byte $41, $1c
	.word @song0ref976
	.byte $ff, $bf
@song0ch9loop:
	.byte $00, $42
	.word @song0ch9loop
@song0ch10:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
@song0ref1200:
	.byte $86, $29, $89, $82, $36, $89, $84, $34, $89, $82, $36, $89, $80, $2a, $89, $82, $36, $89, $84, $34, $89, $82, $36, $89
	.byte $86, $29, $89, $82, $36, $89, $84, $34, $89, $82, $36, $89, $80, $2a, $89, $82, $36, $89, $84, $34, $89, $82, $36, $89
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $18
	.word @song0ref1200
	.byte $80, $31, $89, $82, $36, $89, $80, $2d, $89, $2b, $89
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $18
	.word @song0ref1200
	.byte $80, $31, $89, $82, $36, $89, $80, $2d, $89, $2b, $89
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $18
	.word @song0ref1200
	.byte $80, $31, $89, $82, $36, $89, $80, $2d, $89, $2b, $89
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $41, $20
	.word @song0ref1200
	.byte $80, $2e, $89, $82, $36, $89, $84, $34, $89, $80, $2e, $89, $82, $36, $89, $84, $34, $89, $80, $2e, $89, $2e, $89, $2a
	.byte $89, $00, $d1
@song0ch10loop:
	.byte $00, $42
	.word @song0ch10loop
@song0ch11:
	.byte $41, $2c
	.word @song0ref898
@song0ch11loop:
	.byte $00, $42
	.word @song0ch11loop
@song0ch12:
	.byte $41, $2c
	.word @song0ref898
@song0ch12loop:
	.byte $00, $42
	.word @song0ch12loop
@song0ch13:
	.byte $41, $2c
	.word @song0ref898
@song0ch13loop:
	.byte $00, $42
	.word @song0ch13loop
@song0ch14:
	.byte $41, $2c
	.word @song0ref898
@song0ch14loop:
	.byte $00, $42
	.word @song0ch14loop
@song0ch15:
	.byte $41, $2c
	.word @song0ref898
@song0ch15loop:
	.byte $00, $42
	.word @song0ch15loop
@song0ch16:
	.byte $41, $2c
	.word @song0ref898
@song0ch16loop:
	.byte $00, $42
	.word @song0ch16loop
@song0ch17:
	.byte $41, $2c
	.word @song0ref898
@song0ch17loop:
	.byte $00, $42
	.word @song0ch17loop
@song0ch18:
	.byte $41, $2c
	.word @song0ref898
@song0ch18loop:
	.byte $00, $42
	.word @song0ch18loop
@song0ch19:
	.byte $41, $2c
	.word @song0ref898
@song0ch19loop:
	.byte $00, $42
	.word @song0ch19loop
